spring.application.name=product-crud

# Konfigurasi database akan ditambahkan saat praktikum JPA
spring.datasource.url=postgresql://neondb_owner:npg_kEAgcrP3jlK8@ep-fragrant-lab-ammen0tw-pooler.c-5.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_kEAgcrP3jlK8
spring.datasource.driver-class-name=org.postgresql.Driver

# === Konfigurasi Database Postgresql ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true