spring.application.name=product-crud

# Konfigurasi database
# PERBAIKAN: Menambahkan sslmode=require dan stringtype=unspecified
spring.datasource.url=jdbc:postgresql://ep-plain-fog-amthlsqz-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&stringtype=unspecified
spring.datasource.username=neondb_owner
spring.datasource.password=npg_COIao8wt9kFT
spring.datasource.driver-class-name=org.postgresql.Driver

# === Konfigurasi Database Postgresql ===
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true